# Generated by Django 3.0.2 on 2020-01-30 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Enter a nickname (max 8 characters)', max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.AddField(
            model_name='book',
            name='model_pic',
            field=models.ImageField(default='', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Publisher', max_length=50),
        ),
        migrations.CreateModel(
            name='ShippingAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zipcode', models.IntegerField()),
                ('nickname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.User')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccnumber', models.IntegerField()),
                ('nickname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.User')),
            ],
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=1000)),
                ('rating', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.User')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.ManyToManyField(through='catalog.BookRating', to='catalog.User'),
        ),
    ]
