# Generated by Django 3.0.2 on 2020-02-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_shopping_cart_model_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='name',
        ),
    ]
