# Generated by Django 3.0.3 on 2020-02-15 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_shopping_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='ccv',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='expiration',
            field=models.DateField(blank=True, help_text='(MM/YY)', null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='ccnumber',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
