# Generated by Django 3.0.2 on 2020-02-02 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200130_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter a nickname (max 8 characters)', max_length=8)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='shippingaddr',
            name='nickname',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.UserProfile'),
        ),
        migrations.AddField(
            model_name='shippingaddr',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.UserProfile'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.ManyToManyField(through='catalog.BookRating', to='catalog.UserProfile'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.UserProfile'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
