# Generated by Django 3.0.2 on 2020-02-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200215_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='author',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='title',
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='subtotal',
            field=models.FloatField(default='9.99'),
        ),
    ]
