# Generated by Django 3.0.2 on 2020-02-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200215_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
