# Generated by Django 3.0.2 on 2020-02-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200215_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
