# Generated by Django 3.0.2 on 2020-02-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200202_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='model_pic',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
    ]
