# Generated by Django 3.0.2 on 2020-02-16 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter a brief description of the book', max_length=1000),
            preserve_default=False,
        ),
    ]
