# Generated by Django 3.0.2 on 2020-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
