# Generated by Django 3.0.2 on 2020-02-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200202_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'books'},
        ),
        migrations.AlterField(
            model_name='book',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
