# Generated by Django 3.0.2 on 2020-02-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_userprofile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
    ]
