# Generated by Django 3.0.2 on 2020-02-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_delete_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
