# Generated by Django 3.0.2 on 2020-02-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
