# Generated by Django 3.0.2 on 2020-02-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_orderbook_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
