# Generated by Django 3.0.2 on 2020-02-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_shopping_cart_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ratings',
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='ratings',
            field=models.ManyToManyField(to='catalog.BookRating'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='', max_length=25),
        ),
    ]
