# Generated by Django 3.0.2 on 2020-02-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200217_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='orders',
        ),
    ]
