# Generated by Django 3.0.2 on 2020-02-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200217_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orders',
            new_name='items',
        ),
    ]
