# Generated by Django 3.0.2 on 2020-02-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200219_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='order_price',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
