# Generated by Django 3.0.2 on 2020-02-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_remove_orderbook_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='order_price',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
