# Generated by Django 3.0.2 on 2020-03-15 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0028_userprofile_wishlists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_for_later',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='1')),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('subtotal', models.FloatField(default='9.99')),
                ('name', models.CharField(default='Shopping Cart', max_length=100)),
                ('books', models.ManyToManyField(to='catalog.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
