# Generated by Django 3.0.2 on 2020-03-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_saved_for_later'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_for_later',
            name='name',
            field=models.CharField(default='Saved For Later', max_length=100),
        ),
    ]
