# Generated by Django 3.0.2 on 2020-03-16 00:36

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20200315_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='book_total_price',
            field=models.FloatField(default=catalog.models.OrderBook.get_total_book_price),
        ),
    ]
