# Generated by Django 3.0.2 on 2020-03-19 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0031_orderbook_book_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='book_total_price',
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration',
            field=models.DateField(blank=True, help_text='(YYYY-MM-DD)', null=True),
        ),
        migrations.CreateModel(
            name='SaveBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('saved_date', models.DateTimeField()),
                ('saved', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='catalog.OrderBook')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
