# Generated by Django 3.0.2 on 2020-03-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20200319_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='items',
            field=models.ManyToManyField(to='catalog.SaveBook'),
        ),
    ]
