# Generated by Django 3.0.2 on 2020-03-21 22:36

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20200319_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='total_price',
            field=models.FloatField(default=9.99),
        ),
    ]
