# Generated by Django 3.0.2 on 2020-03-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_orderbook_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
