# Generated by Django 3.0.2 on 2020-03-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20200321_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='total_price',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='tot_price',
            field=models.FloatField(default=0.0),
        ),
    ]
