# Generated by Django 3.0.2 on 2020-03-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_savebook_tot_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='tot_price',
        ),
        migrations.RemoveField(
            model_name='savebook',
            name='tot_quantity',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='tot_quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
