# Generated by Django 3.0.2 on 2020-03-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20200321_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='tot_quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
