# Generated by Django 3.0.2 on 2020-03-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20200321_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='tot_quantity',
        ),
    ]
